_target_: src.models.ImageCaptionModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.ImageCaptionNet
  image_embed_net:
    _target_: src.models.components.image_embedding.InceptionNet
    drop_rate: 0.5
    image_features: ${model.net.features}

  text_embed_net:
    _target_: src.models.components.text_embedding.Glove_RNN
    embed_dim: 200
    drop_rate: 0.5
    text_features: ${model.net.features}
    n_layer_rnn: 1
    dataset_dir: ${model.dataset_dir}

  features: 256
  dataset_dir: ${model.dataset_dir}
dataset_dir: ${paths.data_dir}/${data.dataset_name}
