_target_: src.models.components.image_caption_net.ImageCaptionNet
image_embed_net:
  _target_: src.models.components.image_embedding.InceptionNet
  drop_rate: 0.5
  image_features: ${model.net.features}

text_embed_net:
  # _target_: src.models.components.text_embedding.Glove_Transformer
  # embed_dim: 200
  # drop_rate: 0.5
  # num_heads: 10
  # num_encoder_layers: 8
  # num_decoder_layers: 8
  # text_features: ${model.net.features}
  # dataset_dir: ${model.dataset_dir}
  _target_: src.models.components.text_embedding.Glove_Transformer_Encoder
  
features: 256
dataset_dir: ${model.dataset_dir}
